services:
  - type: web
    name: verifireando-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.16.0
      - key: SERVE_FRONTEND
        value: false
      - key: LOG_TO_CONSOLE
        value: true
      - key: MONGODB_URI
        sync: false
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        value: https://verifireando.com
      - key: ALLOWED_ORIGINS
        value: https://verifireando.com,https://www.verifireando.com,https://verifireando.vercel.app
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        value: noreply@verifireando.com
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false

  - type: web
    name: verifireando-frontend
    env: static
    plan: free
    region: oregon
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://verifireando-backend.onrender.com/api
      - key: VITE_SOCKET_URL
        value: https://verifireando-backend.onrender.com